### ISSUE TITLE
back tool mod 

### ISSUE THREAD

**Issue by DuckyCrusader** [kingofaces2/Into-the-Wind#10]
I was wondering if you are able to add the back tools mod cause it would be nice to have more cosmetic mods and it's useable for 1.16.5

**Comment by kingofaces2** [comment]
"This mod is purely Clientside. It will not do anything when installed on a server." -https://ichun.me/mods/back-tools/
Since it is client-sided only it will not be added to the pack since it is built around being server and client friendly.
You can always add the mod to your client if you wish.
